name: show input from workflow_call
on: push
jobs:
  call-reusable:
    uses: ./.github/workflows/reusable.yml
    with:
      name: "Alice"

  display-output:
    needs: call-reusable
    runs-on: ubuntu-latest
    steps:
      - name: Display greeting
        run: |
          echo "Greeting: ${{ needs.call-reusable.outputs.greeting }}"
