# Cancell workflow why ?
# your workflow takes too much time rather than atleast 2 min.
# or you have to wait untill workflows get success of fails and get error
# you can cancell workflows directly on actions in github.

# skip workflows
# if your git commit -m -- commit msg has define a keyword for skip.
# Only that workflows will not triggers.
# ex. git commit -m "Skip Workflow for demo [skip ci]"

name: Skip Workflows for demo
on:
  workflow_dispatch: 
  pull_request: 
    types:  # Just use types for filters the pull requests events like, pull request while pull will be opened or closed.
    # if you dont specify filtered pull requests all activity types under pull will be triggers.
      - opened
  push:       # triggers workflows while push events happens only for master branch.
    branches:
      - master
    # paths-ignore: 
    #   - .github/workflows/fi*
    #   - .github/workflows/test-*
    #   - .github/workflows/run-*
      # OR
    paths:    # triggres workflows while push events happens in specific folder or file in master branch.
      - .github/workflows/event-filters-controll-events.yml
jobs:
  test-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Download Clone Code
        uses: actions/checkout@v4
      - name: Install NodeJS on Runner # By default its installed.
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm Install
        working-directory: second-action-react
        run: npm install # like npm install
      - name: Run React
        run: npm test
        working-directory: second-action-react

  deploy_job:
  # Want to Run this job after run job test successfully first.
  # Use needs: job_name.
    needs: test-job
    runs-on: ubuntu-20.04
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: Install npm and dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Just npm install
        run: npm ci
        working-directory: second-action-react
      - name: Build npm
        run: npm run build
        working-directory: second-action-react



  