name: my-first yml
on:
  workflow_dispatch:
  issues:
    types: 
      - opened
  push:
    branches: 
      - master  

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: install npm v 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: npm ci
        run: npm ci
        working-directory: second-action-react