name: my first pipeline
on: [ push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: install node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: npm ci
        run: npm ci
      - name: npm test
        run: npm run test


  deploy_job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: install npm
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: npm install 
        run: npm ci
      - name: npm build
        run: npm run build