name: my first pipeline
# on: [ push, workflow_dispatch]
on:
  issues:
    types: 
      - opened
  workflow_dispatch:
  push:
    # branches:
    #   - main
    branches-ignore: 
      - main 
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: install node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: npm ci
        run: npm ci
        working-directory: second-action-react
      - name: npm test
        run: npm run test
        working-directory: second-action-react


  deploy_job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: install npm
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: npm install 
        run: npm ci
        working-directory: second-action-react
      - name: npm build
        run: npm run build
        working-directory: second-action-react
        
  build:
    needs: deploy_job
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: npm ci
        run: npm ci
        working-directory: second-action-react
      - name: npm build
        run: npm run build
        working-directory: second-action-react
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: my-test-artifact 