name: Test Project
on: push
jobs:
  test-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Download Clone Code
        uses: actions/checkout@v4
      - name: Install NodeJS on Runner # By default its installed.
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm Install
        # working-directory: .github/workflows
        run: npm install # like npm install
      - name: Run React
        run: npm run dev


  